PP-15 Current Untraked Work
LUGAMAFE/Portfolio pull request #6
Opened 2023-10-18 07:05 UTC by Tort9994

2023-10-29 08:07 UTC, LUGAMAFE requested changes
Uff me tarde un monton checando este PR hay que tratar de evitar PR asi de enormes en el futuro cueste lo que cueste. De hecho hay muchas cosas que no anote aqui ya que por el momento tienes suficientes cambios por hacer.

2023-10-29 08:07 UTC, LUGAMAFE commented on src/components/neumorphic/RealNeumorphicElement.jsx
> +      });
```suggestion

```
Esta implementacion aun no es correcta y esta mal planteada, la rama de main se tiene que tratar como si la rama ya estuviera en produccion y no debemos mandar funcionalidades que estan mal plenteadas desde un punto de vista de arquitectura, funcionamiento y orden de codigo. Porfavor borra este codigo que de hecho estoy seguro que es lo que hace que cuando cambiemos de forma automaticamente hace que regrese el elemento a la forma que tenia anteriormente.

2023-10-29 08:07 UTC, LUGAMAFE commented on src/components/neumorphic/RealNeumorphicElement.jsx
> +        className={
Mismo comentario que antes si esto aun no funciona al 100 no lo mandes esperate al siguiente ticket en donde se supone se solucionara.

2023-11-02 08:08 UTC, Tort9994 commented on .stylelintrc
> +        "ignore": ["css-nesting", "intrinsic-width"]
me sale este warning que no me deja subir el commit aunque necesite esas propiedades: Unexpected browser feature "intrinsic-width" is only partially supported by Firefox 117  plugin/no-unsupported-browser-features :c

2023-11-02 08:14 UTC, Tort9994 commented on src/components/ContactSection.jsx
> +                <image href="../../assets/images/Vector-13.svg" />
sobre ese contenedor si se puede cortar una parte del borde y que se siga viendo el fondo? creo que es mejor usar el svg pero sino veo como cambiarlo

2023-11-03 05:52 UTC, LUGAMAFE commented on .stylelintrc
> +        "ignore": ["css-nesting", "intrinsic-width"]
Muestrame en donde te marca eso porfavor mandame captura, en que parte del css, en que archivo en que lineas de codigo

2023-11-03 07:23 UTC, LUGAMAFE reviewed
Super bien Primo la verdad muchas gracias, se nota que si le pusiste atencion a los comentarios que te puse y no senti que algo muy grande se te fuera. Muchas gracias por tu esfuerzo, espero este PR sirva como experiencia para los siguientes. 

Solo ayudame a corregir los pequeños comentarios que puse antes de mergear esta rama

2023-11-03 07:23 UTC, LUGAMAFE commented on package.json
> +    "typeCheck": "tsc"
```suggestion
    "typecheck": "tsc"
```
vamos a cambiarlo a solo minusculas siento que es mas facil usar este comando asi

2023-11-06 18:34 UTC, LUGAMAFE approved these changes

2023-11-06 18:35 UTC, merged