Task/PP-16_refactor-js-code-to-typescript
LUGAMAFE/Portfolio pull request #8
Opened 2023-11-07 08:19 UTC by Tort9994

## Summary

### Problem

there was a lot of code deppending all just on duck typeing of javascript, so there could be a lot of type mistakes of that 

### Solution

now all code was change to typescript so all dependencies recive the information they nedd

## Acceptance Criteria

### Requirements checklist

- [ ] All the js code must be typescript code

2023-12-21 18:27 UTC, LUGAMAFE requested changes

2023-12-21 18:27 UTC, LUGAMAFE commented on src/components/neumorphic/Configuration.tsx
> +  const handleDirection = (direction: number): void => {
cambia esta funcion a algo como esto:
```js
const handleDirection = (direction: number): void => {
  updateContextConfigProp('lightSource', +name);
  const angleMap = {
    3: 45,
    4: 145,
    1: 225,
    2: 315
  };
  const angle = angleMap[direction];
  if (angle !== undefined) {
    setAngle(angle);
  }
```

2023-12-21 18:27 UTC, LUGAMAFE commented on src/components/neumorphic/Configuration.tsx
> +  const handleDirectionAngle = (angulo: number) => {
Cambia esta funcion a algo como esto:

```js 
const handleDirectionAngle = (angulo: number) => {
  const ranges = [
    { min: 0, max: 90, lightSource: 3 },
    { min: 90, max: 180, lightSource: 4 },
    { min: 180, max: 270, lightSource: 1 },
    { min: 270, max: 360, lightSource: 2 }
  ];

  const match = ranges.find(range => angulo >= range.min && angulo < range.max);
  if (match) {
    updateContextConfigProp('lightSource', match.lightSource);
  } else {
    return -1;
  }
};
```

2023-12-21 18:27 UTC, LUGAMAFE commented on src/components/neumorphic/Configuration.tsx
> +            handleDirectionAngle(newAngle ? newAngle : 0);
```suggestion
            setAngle(newAngle || 0);
            handleDirectionAngle(newAngle || 0);
```

2023-12-21 18:27 UTC, LUGAMAFE commented on src/components/neumorphic/Configuration.tsx
> +          lightSource={contextConfig.lightSource ? contextConfig.lightSource : 1}
```suggestion
          lightSource={contextConfig.lightSource | 1}
```

2023-12-21 18:27 UTC, LUGAMAFE commented on src/components/neumorphic/Configuration.tsx
> +        value={contextConfig.size ? contextConfig.size : 100}
```suggestion
        value={contextConfig.size | 100}
```

2023-12-21 18:27 UTC, LUGAMAFE commented on src/components/neumorphic/Configuration.tsx
> +        value={contextConfig.distance ? contextConfig.distance : 45}
```suggestion
        value={contextConfig.distance | 45}
```

2023-12-21 18:27 UTC, LUGAMAFE commented on src/components/neumorphic/Configuration.tsx
> +        value={contextConfig.intensity ? contextConfig.intensity : 0.15}
```suggestion
        value={contextConfig.intensity | 0.15}
```

2023-12-21 18:27 UTC, LUGAMAFE commented on src/components/neumorphic/Configuration.tsx
> +        value={contextConfig.blur ? contextConfig.blur : 90}
```suggestion
        value={contextConfig.blur | 90}
```

2023-12-21 18:27 UTC, LUGAMAFE commented on src/components/neumorphic/LightSourceSelector.tsx
> +    const direction = Number((event.target as HTMLInputElement).name);
```suggestion
    const direction = Number((event.target as HTMLButtonElement).name);
```

2023-12-21 18:27 UTC, LUGAMAFE commented on src/components/neumorphic/LightSourceSelector.tsx
> +        ></button>
Mejorar el codigo repetido y la accesibilidad de todos los botones haciendo algo como esto:
```suggestion
  {directions.map((direction) => (
    <button
      key={direction}
      className={`${style.arrow} ${lightSource === direction ? style.active : ''}`}
      onClick={handleClick}
      name={`${direction}`}
    ></button>
  ))}
```

2023-12-21 18:27 UTC, LUGAMAFE commented on src/components/neumorphic/LightSourceSelector.tsx
> +    <div className={`${style.row} ${style.label}`} style={{ margin: '12px 0px 8px' }}>
Evita estos estilos de linea si puedes y muevelo a su respectiva clase en los css modules
```suggestion
    <div className={`${style.row} ${style.label}`}>
```

2023-12-21 18:27 UTC, LUGAMAFE commented on src/interfaces/neomorphism.ts
Renombra esta carpeta a algo como types/neomorphism.ts

Este archivo hay que mejorarlo mucho e importar cosas que estan regadas por todos lados que se podrian unifiacar aqui y solo importar en otros archivos lo que se necesite de aqui

2023-12-21 18:27 UTC, LUGAMAFE commented on src/components/neumorphic/ConfigurationRow.tsx
> +  step?: string | number;
Deshaceste de todos los string que no sean necesarios, ya solo deja number si es posible
```suggestion
  value: number;
  min?: number;
  max?: number;
  step?: number;
```

2023-12-21 18:27 UTC, LUGAMAFE commented on src/components/neumorphic/RealNeumorphicElement.tsx
> +      if (!contextConfig.intensity) return;
estas segura de parar la funcion aqui? no estoy seguro como afecte esto

2023-12-21 18:27 UTC, LUGAMAFE commented on src/components/neumorphic/ShapeSwitcher.tsx
> +  shape?: 'concave' | 'convex' | 'level' | 'pressed' | 'flat' | null;
de nuevo aqui estos types de 'concave' | 'convex' | 'level' | 'pressed' | 'flat' ya lo habiamos visto en otros archivos asi que mejor importalo de `types/neomorphism.ts`

2023-12-21 18:27 UTC, LUGAMAFE commented on src/utils/index.ts
> +export function getIntFormValue(form: 'concave' | 'convex' | 'level' | 'pressed' | 'flat'): number {
De nuevo importa estos tipos de `'concave' | 'convex' | 'level' | 'pressed' | 'flat'` desde el enum que deberia estar en  `types/neomorphism.ts`

2023-12-21 18:27 UTC, LUGAMAFE commented on src/main.tsx
>    // </React.StrictMode>
Bro hay que activar el React.StrictMode no se por que se desactivo: 
```js
ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
     <PortfolioApp />
  </React.StrictMode>
);
```

2023-12-21 18:28 UTC, LUGAMAFE requested changes
Te deje varios comentarios 🥴 pero en general todo good

2024-01-02 08:13 UTC, LUGAMAFE requested changes
Mucho mucho mejor pero creo que hay mejoras que podemos hacer.

2024-01-02 08:13 UTC, LUGAMAFE commented on src/components/neumorphic/ShapeSwitcher.tsx
Este componente se puede refactorizar aun mas:
```js
import { MouseEvent } from 'react';
import style from '../../style/sass/components/neomorphism/configuration.module.scss';
import { FormShape } from '../../types/neomorphism';
import Concave from '../svg/concave.svg';
import Convex from '../svg/convex.svg';
import Flat from '../svg/flat.svg';
import Level from '../svg/level.svg';
import Pressed from '../svg/pressed.svg';

export interface ShapeSwitcherProps {
  shape?: FormShape;
  setShape: (name: FormShape) => void;
}

const ShapeButton = ({ shape, setShape, name, title, Image }) => (
  <button
    className={shape === name ? style.active : ''}
    onClick={() => setShape(name)}
    name={name}
    title={title}
  >
    <img src={Image} alt={title} />
  </button>
);

const ShapeSwitcher = ({ shape, setShape }: ShapeSwitcherProps) => {
  const shapes = [
    { name: 'concave', title: 'Concave', Image: Concave },
    { name: 'convex', title: 'Convex', Image: Convex },
    { name: 'level', title: 'Level', Image: Level },
    { name: 'pressed', title: 'Pressed', Image: Pressed },
    { name: 'flat', title: 'Flat', Image: Flat },
  ];

  return (
    <>
      <div className={`${style.row} ${style.label}`}>
        <label>Form: </label>
      </div>
      <div className={style.row}>
        <div className={style.shapeSwitch}>
          {shapes.map((btnShape) => (
            <ShapeButton
              key={btnShape.name}
              shape={shape}
              setShape={setShape}
              name={btnShape.name}
              title={btnShape.title}
              Image={btnShape.Image}
            />
          ))}
        </div>
      </div>
    </>
  );
};

export default ShapeSwitcher;
```

2024-01-02 08:13 UTC, LUGAMAFE commented on src/utils/index.ts
> +export function getIntFormValue(form: 'concave' | 'convex' | 'level' | 'pressed' | 'flat'): number {
me dejaste en veido completamente 🥴

2024-01-02 08:13 UTC, LUGAMAFE commented on src/components/ProyectSection/DescriptionProyect.tsx
Creo que este archivo  deberia llamarase ProyectDescription y no alrevez

2024-01-02 08:13 UTC, LUGAMAFE commented on src/components/neumorphic/NeuTooltipTool.tsx
Intenta refactorizar este compoente asi como los otros ejemplos que te he dado, siento que esta muy complejo y puede tener mejoras

2024-01-02 15:30 UTC, Tort9994 commented on src/types/neomorphism.ts
> +  id?: string;
Como veo es que no todos los neomorphic elements deben llevar de forma obligatoria un id solo los que lo necesiten para una acción especifica

2024-01-03 04:16 UTC, LUGAMAFE approved these changes, later dismissed

2024-01-03 04:16 UTC, LUGAMAFE commented on src/components/Navbar/LanguageButton.tsx
> +  onClick: (id: string) => void;
porque? ya sabemos que para esto hay que crear interfaces. No pongas los tipos sueltos porfavor, sigue un estandar

2024-01-23 04:41 UTC, LUGAMAFE approved these changes

2024-01-23 04:41 UTC, merged